-name: Understanding precedence of variables
 hosts: all
 become: yes
 vars:
    USER_NAME: tests_user
    COMMENT: Variable from playbook
 tasks:
- name: create a user
  user:
     name: “{{USER_NAME}}”
     comment: “{{COMMENT}}”
   register: USER_OUT

 - debug:
      var: USER_OUT.name

- debug:
      var: USER_OUT.comment
