- name: Learning Fact Variables
  hosts: all
  tasks:
     - name: Print OS names
       debug:
            var: ansible_distribution

     - name: Print Memory Details
        debug:
            var: ansible_memory_mb

     - name: Print Real Memory Details
       debug:
           var: ansible_memory_mg.real.free

     - name: Print Processor Name
       debug:
           var: ansible_processor[2]
